CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

-- Table structure for table 'classification'
CREATE TABLE IF NOT EXISTS public.classification
(
    classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    classification_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
)

--Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inv_make character varying COLLATE pg_catalog."default" NOT NULL,
    inv_model character varying COLLATE pg_catalog."default" NOT NULL,
    inv_year character(4) COLLATE pg_catalog."default" NOT NULL,
    inv_description text COLLATE pg_catalog."default" NOT NULL,
    inv_image character varying COLLATE pg_catalog."default" NOT NULL,
    inv_thumbnail character varying COLLATE pg_catalog."default" NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying COLLATE pg_catalog."default" NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    account_firstname character varying COLLATE pg_catalog."default" NOT NULL,
    account_lastname character varying COLLATE pg_catalog."default" NOT NULL,
    account_email character varying COLLATE pg_catalog."default" NOT NULL,
    account_password character varying COLLATE pg_catalog."default" NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
)

-- Data for table classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- 4. Update GM Hummer description (Replace 'small interiors' with 'a huge interior')
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 6. Update all records to add "/vehicles" to file paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');